apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: fluentd-ds
  #namespace: mynamespace
spec:
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          #image: gcr.io/google-containers/fluentd-elasticsearch:1.20
           image: fluentd:v1.16-debian-1
  selector:
    matchLabels:
      app: fluentd
